WITH T1 AS(
SELECT
A.LOG_DATE,
A.STORAGE_ARRAY_ID,
A.ARRAY_NAME,
A.RAW_CAPACITY_GB,
A.RAW_ALLOCATED_GB,
A.USABLE_INTERNAL_CAPACITY_GB,
A.USABLE_USED_CAPACITY_GB,
A.USABLE_FREE_CAPACITY_GB
FROM APS_V_STORAGE_ARRAY_LOG A, APS_V_STORAGE_ARRAY B
WHERE A.LOG_DATE BETWEEN SYSDATE - 60 AND SYSDATE
AND  A.LOG_DATE <= trunc(SYSDATE)-7
AND A.STORAGE_ARRAY_ID = B.STORAGE_ARRAY_ID
AND B.VENDOR_NAME LIKE '%Pure%'
ORDER BY 1,2
), -- SELECT * FROM T1
CONTROL1 AS(
SELECT
LOG_DATE,
EXTRACT(DAY FROM LOG_DATE) CDAY,
EXTRACT(MONTH FROM LOG_DATE) CMON,
EXTRACT(YEAR FROM LOG_DATE) CYR,
STORAGE_ARRAY_ID,
ARRAY_NAME,
RAW_CAPACITY_GB,
RAW_ALLOCATED_GB,
USABLE_INTERNAL_CAPACITY_GB,
USABLE_USED_CAPACITY_GB,
USABLE_FREE_CAPACITY_GB
FROM T1
),
CONTROL2 AS(-- GETS THE LAST DAY OF EACH MONTH IN RESULTS FROM PREV. BLOCK
SELECT
MAX(CDAY) MDAY,
STORAGE_ARRAY_ID,
CMON,
CYR
FROM CONTROL1
GROUP BY STORAGE_ARRAY_ID,CMON, CYR
ORDER BY CMON DESC
)
SELECT
TO_CHAR(C1.LOG_DATE, 'MM/DD/YYYY HH:MI:SS') CDATE,
C1.STORAGE_ARRAY_ID,
C1.ARRAY_NAME,
C1.RAW_CAPACITY_GB,
C1.RAW_ALLOCATED_GB,
C1.USABLE_INTERNAL_CAPACITY_GB,
C1.USABLE_USED_CAPACITY_GB,
C1.USABLE_FREE_CAPACITY_GB
FROM CONTROL1 C1, CONTROL2 C2
WHERE C1.STORAGE_ARRAY_ID = C2.STORAGE_ARRAY_ID
AND C1.CDAY=C2.MDAY
AND C1.CMON=C2.CMON
AND C1.CYR =C2.CYR
ORDER BY 2,1
